### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by otech-nl** [bastibe/org-static-blog#12]
Hello Bastian, 

Just wanted to say thanks for providing us with this excellent bit of software. I have tried many alternatives (e.g. Nikola) but this was by far the simplest solution that was most easy to configure.

As a suggestion to other users: I (ab)use drafts as static pages. For example, I have a `drafts/index.org` that becomes my landing page (after changing `org-static-blog-index-file` to `"blog.html"`).

For more, have a look at my setup for github pages at https://github.com/otech-nl/otech-nl.github.io/

Regards,

René

**Comment by bastibe** [comment]
Thank you!

I, too, abuse the drafts directory for static pages, which is why there is the variable `org-static-blog-drafts-directory`, which lets you rename it, if you so desire.

Little thank you notes like this mean a lot!

If you want to, you can create a pull request to add your page to the *Examples* node in the README.
