### ISSUE TITLE
dir-locals aren't being applied

### ISSUE THREAD

**Issue by matthewbauer** [bastibe/org-static-blog#22]
I have a .dir-locals.el file in the root of my blog that looks like this:

```
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((nil
  (org-static-blog-page-preamble . "<h1><a class=\"name\" href>Matthew Bauer</a> ◌ <a href=\".\">Blog</a> ◌ <a class=\"name\" href=\"feed.xml\">RSS</a></h1>")
  (org-static-blog-publish-title . "Matthew Bauer’s Blog")
  (org-static-blog-publish-url . "https://matthewbauer.us/blog/")
  (org-static-blog-rss-file . "feed.xml")
  (org-static-blog-index-length . 1)
  (org-static-blog-page-header . "  <meta name=\"author\" content=\"Matthew Bauer\">
  <meta name=\"viewport\" content=\"initial-scale=1,width=device-width,minimum-scale=1\">
  <link rel=\"stylesheet\" href=\"../style.css\">")))
```

They don't seem to be used by org-static-blog-publish. The values are set in the buffer, but org-static-blog uses the custom one for some reason.

**Comment by bastibe** [comment]
I believe that `org-static-blog-publish` is not executed in `org-static-blog-{publish,posts,drafts}-directory`, which is why it is not picking up your .dir-locals.el. This would be a neat feature, though, and I would be grateful for a pull request that adds this. Probably for the `org-static-blog-posts-directory`.
